### ISSUE TITLE
Add optional IP selection handler

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/node#23]
Add an optional IP selection handler to the SDK client initialization step which accepts the request context and expects returning an IP.

Add a default handler for this which looks at the `X-Forwarded-For` header and falls back to the source IP.

The resulting IP is the IP for which details are fetched.

**Comment by UmanShahzad** [comment]
Closing as this actually only applies to middleware SDKs (e.g. Django/Rails/Express/etc), not language SDKs.

**Comment by cdeath** [comment]
@UmanShahzad not sure if this is the right place to ask this, but, is there a way to specify which header contains the client IP instead of making it part of the endpoint?

**Comment by UmanShahzad** [comment]
@cdeath I think you're asking about whether the HTTP API (e.g. `https://ipinfo.io/8.8.8.8`) has this feature, right? No, it won't parse arbitrary headers that you somehow specify looking for a client IP AFAIK. You can just parse the header in question at the call site the way you want and then send that as the IP in the request. E.g.:

```js
let ipFromMyHeader = req.headers.get('X-Custom-Header')
ipinfoClient.lookupIp(ipFromMyHeader)
```

**Comment by cdeath** [comment]
@UmanShahzad hey!

yes, i was referring to the HTTP API.

i am proxying the request to a local endpoint and what i get is the cdn ip, but the cdn sends the client ip in a specific header... so it would be cool (i.e. might solve my problem ha ha) to let the API know where to extract the ip address.

**Comment by UmanShahzad** [comment]
@cdeath If the CDN is using some custom header, you can run some logic in your local endpoint to parse that header for the IP and give it to the API.

If the header's value is literally just the IP string, then you can pass that directly into the API as in the example I gave above.

**Comment by cdeath** [comment]
@UmanShahzad it's a Netlify rewrite rule... but i'll see if i can run a function or do something with this...

**Comment by UmanShahzad** [comment]
@cdeath happy to help.

> btw... is there a proper channel to discuss API functionality?

There's no public forum yet no, but the API is well documented at https://ipinfo.io/developers. If you have some custom requirements or feature suggestions then support@ipinfo.io is probably the best place right now.
