### ISSUE TITLE
IPinfo.Lrucache example throws constructor error.

### ISSUE THREAD

**Issue by damdinsharav** [ipinfo/node#31]
I'm trying use example cache.
However I'm getting following error.
```
TypeError: IPinfo.LruCache is not a constructor
```

```
const IPinfo = require("node-ipinfo");

let cacheOptions = {
    max: 5000,
    maxAge: 24 * 1000 * 60 * 60,
};
let cache = new IPinfo.LruCache(cacheOptions);
let ipinfo = new IPinfo("myToken", cache);
```
Nodejs version: v14.16.0

**Comment by UmanShahzad** [comment]
Sorry about that, seems we didn't properly test the non-ES module use case, and so the LruCache import was not being included in it.

Should be fixed by https://github.com/ipinfo/node/commit/f1b90bafb32fb84629624e8a5d6a1ae600ecea99 - v2.0.2 is uploaded.
