### ISSUE TITLE
I can't import IPinfoWrapper. IPinfoWrapper is undefined

### ISSUE THREAD

**Issue by nuno-cunha-dev** [ipinfo/node#44]
First of all I wanted to say that I just created a new project in nest.js so i am using typescript instead of javascript.

I ran `npm install node-ipinfo`

And then I created a service that returns the city via IP:
```
import IPinfoWrapper from 'node-ipinfo';
import { Injectable } from '@nestjs/common';

@Injectable()
export default class IpInfoProvider {
  getCity(): string {
    console.log(IPinfoWrapper);
    const ipinfoWrapper = new IPinfoWrapper('token');
    return 'city-name-test';
  }
}
```
As you can see, I'm logging the IPinfoWrapper imported class, but I'm getting `undefined`, this means that when instantiating I get the following error: `TypeError: node_ipinfo_1.default is not a constructor`

The only way I'm able to instantiate the IPinfoWrapper is to go to the `node_modules/node-ipinfo/index.js` file and change the return https://github.com/ipinfo/node/blob/4496107d2bd2239d27aae7cbb994f2a773f86d52/index.js#L7
from: `return m.default;`
to `return m;`

**Comment by UmanShahzad** [comment]
I've tried reproducing this in a fresh TypeScript project and I can't seem to. https://github.com/ipinfo/node/blob/master/test-app/ipinfo.ts

But this could have something to do with not properly detecting ES modules, as the `index.js` you modified above was not being generated by typescript itself.

I've pushed a `3.0.0` version which makes it so we use a typescript-generated `index.js` file. Can you upgrade and try again?

**Comment by nuno-cunha-dev** [comment]
Thank you very much. 
With the new version(3.0.0) everything works fine.

**Comment by jacobg** [comment]
This same error occurred for me when using Nuxt. Transpiling it resolved the issue:
```javascript
export default defineNuxtConfig({
  build: {
    // https://github.com/nuxt/framework/discussions/1194#discussioncomment-1499595
    transpile: ['node-ipinfo']
  },
})
```
