### ISSUE TITLE
Property `bogon` is missing from the `IPinfo` interface.

### ISSUE THREAD

**Issue by HiFaraz** [ipinfo/node#48]
Getting this error when I check for a `bogon` response: `Property 'bogon' does not exist on type 'IPinfo'.ts(2339)`.

However `bogon` is a valid response property according to your documentation. From https://ipinfo.io/developers/data-types#ip-type-data:

```
If the IP is an anycast or a bogon, the API returns a field indicating that.

Bogon Address Information

curl ipinfo.io/127.0.0.1?token=a3989e849337bf

{
  "ip": "127.0.0.1",
  "bogon": true
}
```

**Comment by UmanShahzad** [comment]
Thanks! See v3.0.1.
