### ISSUE TITLE
Lru cache types are causing an error in tsc compile, Including third party type dev dependencies as  dependencies should fix

### ISSUE THREAD

**Issue by elsowiny** [ipinfo/node#51]
node_modules/node-ipinfo/dist/src/cache/lruCache.d.ts:1:25 - error TS7016: Could not find a declaration file for module 'lru-cache'. 'C:/Users/elsow/Documents/Projs/adminAuth/node_modules/lru-cache/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lru-cache` if it exists or add a new declaration (.d.ts) file containing `declare module 'lru-cache';`

1 import { Options } from "lru-cache";

fixed this by npm i --save-dev @types/lru-cache for my overall application, but I know some other packages include third party types as dependencies to avoid this error

**Comment by UmanShahzad** [comment]
Closed by https://github.com/ipinfo/node/pull/52
