### ISSUE TITLE
Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by lynchem** [ipinfo/node#59]
Hi, we've seen this exception fire a few times now over the past months and it's unfortunately not getting handled and crashing our server 😢 . 

We think a simple try/catch around the JSON.parse in IpinfoWrapper.ts:91 would do the trick. See callstack below. Let me know if you need anything else from us. 

```
message: Unexpected token < in JSON at position 1
stack:
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/var/app/current/programs/server/npm/node_modules/node-ipinfo/dist/src/ipinfoWrapper.js:91:43)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at TLSSocket.socketCloseListener (_http_client.js:441:11)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)
```

**Comment by UmanShahzad** [comment]
It's likely crashing at that JSON parsing step because of a 5xx error. But we'd still throw an error even on a 429 status or some other 4xx/5xx status - is your code able to handle that error when thrown?

**Comment by lynchem** [comment]
Thanks for responding so quickly. We can handle any error from the service but this doesn't come back to our code, it's inside an event listener in your package which doesn't have a try/catch around it.

**Comment by UmanShahzad** [comment]
Oh I see, okay. Pushed a v3.1.1 that should handle the 4xx/5xx case properly and delegate to code that rejects the promise instead of throwing an error, so that should fix it. If something persists, we can try wrapping all the code inside of the event listener too.

Lemme know if anything comes up after this.
