### ISSUE TITLE
getBatch doesn't report 403 response

### ISSUE THREAD

**Issue by tstibbs** [ipinfo/node#62]
# Report

The `getBatch` function hides a 403 response from server.

For example, if the provided token is invalid the API returns a 403 error. However this is not passed through to the output of the `getBatch` function.

Note however that `lookupIp` does throw an error in this case.

# How to reproduce

```
import { IPinfoWrapper } from "node-ipinfo"

const ipinfo = new IPinfoWrapper('malformed token')

await ipinfo.getBatch(['8.8.8.8']) //returns {}
await ipinfo.lookupIp('8.8.8.8') //throws error with the 403 error from the server
```

# Expected behaviour

The `getBatch` function should give some indication that the call has failed (e.g. by throwing an error or including some error data in the returned response).

# Actual behaviour

`getBatch` returns an empty map (i.e. `{}`).

# Impact

Difficult to spot when the passed token value is malformed (because it just looks like the IPs could not be found).

**Comment by UmanShahzad** [comment]
Thanks for finding this. @rm-Umar can you try a fix for this?
