### ISSUE TITLE
v3.4.5 installation omits dist directory

### ISSUE THREAD

**Issue by charleskoehl** [ipinfo/node#80]
yarn add node-ipinfo@3.4.4 works, adding the dist directory plus LICENSE, package.json, README.md

yarn add node-ipinfo@3.4.5 omits the dist directory

**Comment by UmanShahzad** [comment]
Sorry about that - we added CI/CD for pushes and it gave a bad push. Fixed that and released v3.4.6 - https://www.npmjs.com/package/node-ipinfo?activeTab=versions

Deprecated v3.4.5.
