### ISSUE TITLE
v3.4.5 Missing type declaration for node-ipinfo

### ISSUE THREAD

**Issue by teliov** [ipinfo/node#81]
Building with typescript results in this error (looks to be introduced with the latest release):

```bash
error TS2307: Cannot find module 'node-ipinfo' or its corresponding type declarations.
```

**Comment by UmanShahzad** [comment]
Sorry about that - we added CI/CD for pushes and it gave a bad push. Fixed that and released v3.4.6 - https://www.npmjs.com/package/node-ipinfo?activeTab=versions

Deprecated v3.4.5.
