### ISSUE TITLE
Use Fetch API instead of node's http(s) package

### ISSUE THREAD

**Issue by tyteen4a03** [ipinfo/node#82]
To enable compatibility with non-Node environments (e.g. Cloudflare Workers), it would be nice if this library can switch to using the Fetch API instead of node's http/https packages.

I had a glance at the code and I don't think there's anything within that requires usage of http or https.

**Comment by UmanShahzad** [comment]
Thanks, we could do that. Putting it on the agenda.

**Comment by MerouaneBali-OscarsFarm** [comment]
+1 this. Would love to see it. Pretty good library other than that.

**Comment by zxfrank** [comment]
+1 using fetch would by default support the system proxy

**Comment by zxfrank** [comment]
+1 using fetch (node-fetch) would be nice!

I don't know if node-fetch has native system proxy support right now but we managed it with a wrapper:

obviously the `cfg.proxy.custom` part is optional. 
```
const fetch=(()=>{
	const
	urlP                        = require('url'),
	_fetch			= require("node-fetch"),
	HttpsProxyAgent	= require("https-proxy-agent");
	return (url,options={})=>{
		return new Promise((resolve, reject) => {
			var c = new AbortController();
			var timer = setTimeout(function () {
				c.abort(new Error('TIMEOUT'));
			}, options.timeout || 1000 * 60 * 5);
			let _p=process.env.https_proxy?new HttpsProxyAgent(process.env.https_proxy):null;
			if(cfg?.proxy?.custom){
				let _h=urlP.parse(url, true);
				for(let i of cfg.proxy.custom){
					if(!i?.reg) continue;
					let _re=new RegExp(i.reg);
					if(_h.hostname.match(_re)?.length){
						_p=new HttpsProxyAgent(i.prox)
						break;
					}
				}
			}
			_fetch(url,{...options, signal: c.signal, agent: _p })
			.then(value => {
				clearTimeout(timer)
				resolve(value)
			})
			.catch(reason => {
				clearTimeout(timer)
				reject(reason)
			})
		});
	}
})()
```
