### ISSUE TITLE
Lru cache types are causing an error in tsc compile

### ISSUE THREAD

**Issue by bskimball** [ipinfo/node#84]
Compilation Errors:

"Could not find a declaration file for module 'lru-cache'."

Try `npm i --save-dev @types/lru-cache` if it exists or add a new declaration (.d.ts) file containing `declare module 'lru-cache';`

5 export { Options } from "lru-cache";

Even after I install @types/lru-cache I get the same error

**Comment by UmanShahzad** [comment]
Thanks for the report @bskimball. The `lru-cache` version we were using here was v6 which didn't have its own native types, Upgraded it to v7 which has its own types.

Can you check v3.5.0 which we just pushed to fix this?

**Comment by bskimball** [comment]
Thanks, this is resolved.
